# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a6cdeeae33910a2a30d5b3216ad38c24a64526df7a855d41838ed531f1bbdf8f014b8baea514877830c8f73bfca054514ed5f93fef85585136a6bb2923d94654

test:
  secret_key_base: 09fff2af81b148de218171f9531f7a2d0023632cfd8bc44ba4f06bf8996c8b287321f9fc99d7f9764e83218a614a71b0e852f3ba6084eaaabab50d650c1675ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
